export enum SCREEN_NAMES {
  HOME_SCREEN = 'HOME_SCREEN',
  ANIMATION1_SCREEN = 'ANIMATION1_SCREEN',
  GESTURE1_SCREEN = 'GESTURE1_SCREEN',
  GESTURE2_SCREEN = 'GESTURE2_SCREEN',
  ANIMATION2_SCREEN = 'ANIMATION2_SCREEN',
  GESTURE3_SCREEN = 'GESTURE3_SCREEN',
}
